#!/bin/sh

# Save the current winid so we know what to switch back to from emacs.
# client_winid=$(current-winid)

# Switch to emacs and wait for editing to be completed.

# emacsclient -c -a fe "$@" && wmctrl -xa emacs
#wmctrl -xa emacs || emacsclient -c -e "(shell-command \"wmctrl -xa emacs\")"
wmctrl -a emacs || emacs

# Switch back to window from which emacsclient was invoked.
# wmctrl -ia $client_winid

