alias l='ls -F --color=auto'
alias ls='ls -F --color=auto'
alias ll='ls -lFh --color=auto'
alias la='ls -aF --color=auto'
alias lla='ls -laFh --color=auto'

alias _='sudo'
alias edit='$EDITOR'
alias vim='nvim'
alias vi='nvim'
alias free='free -h'
alias shutdown='sudo shutdown -h now'
alias h='history'
alias t='tmux'
alias r='source ~/.bashrc'
alias open='xdg-open $1 2>>/dev/null'

alias grep='grep --color=auto'
alias info='info --vi-keys'
alias copy='xclip -i'
alias past='xclip -o'

#alias pacman='pacman --color=auto'
#alias pacaur='pacaur --color=auto'
#alias rm-orphans='sudo pacman -Rns $(pacman -Qtdq)'

# alias emacs='emacsclient --alternate-editor="" -c "$@"'
alias wg='wordgrinder'
alias ccat='pygmentize -g'
