alias l='ls -F --color=auto'
alias ls='ls -F --color=auto'
alias ll='ls -lFh --color=auto'
alias la='ls -aF --color=auto'
alias lla='ls -laFh --color=auto'

alias _='sudo'
alias edit='$EDITOR'
alias e='$EDITOR'
alias vim='nvim'
alias vi='nvim'
alias free='free -h'
alias h='history'
alias r='source ~/.profile'
alias q='exit'
alias open='xdg-open $1 2>>/dev/null'

alias grep='grep --color=auto'
alias info='info --vi-keys'

alias wg='wordgrinder'
alias ccat='pygmentize -g'
